### ISSUE TITLE
来自小白的提问。

### ISSUE THREAD

**Issue by ty859555470** [BlueCocoa/DPlayer-WordPress#1]
B站弹幕是不是这么写bilibili=“4105447”还是bilibili=“https://api.prprpr.me/dplayer/bilibili?aid=4105447”
都不显示呢！

**Comment by BlueCocoa** [comment]
呜喵w

看了一下，是我把bilibili的地址放错位置了qwq

在[v1.1.3](https://github.com/BlueCocoa/DPlayer-WordPress/releases/tag/v1.1.3) 中已经修好了www

(写bilibili="4105447"这样就好~)

**Comment by BlueCocoa** [comment]
在[ v.1.14 ](https://github.com/BlueCocoa/DPlayer-WordPress/releases/tag/v1.1.4)里又扩展了一下bilibili参数支持的格式。

**Comment by ty859555470** [comment]
嗯，我去看看
