### ISSUE TITLE
弹幕无法正常工作

### ISSUE THREAD

**Issue by Pacius** [BlueCocoa/DPlayer-WordPress#11]
若`Danmaku URL` 写为 `https://api.prprpr.me/dplayer`
弹幕无法加载，显示Request was unsuccessful:404，能在视频上显示弹幕，但是没有被弹幕库接收存储；

若`Danmaku URL` 写为 `https://api.prprpr.me/dplayer/v3`
弹幕无法加载，显示Request was unsuccessful:0，能在视频上显示弹幕，但是没有被弹幕库接收存储；

然后尝试用Dplayer-node自建一个，使用上面v3链接形式，发现能与Dplayer-node正常连接，每当用户访问视频，redis 反馈了`set damaku字符串` ，但发送弹幕也是上面那种相同错误。

但注意到了一点，在用户发出弹幕时，视频所在服务器向Dplay-node发出的链接构成似乎有问题，
用户访问时的链接为`/?id=字符串`，但当用户发送弹幕时，该链接变成了`/`，我想应该有个字符串吧，

请大佬帮助一下

**Comment by BlueCocoa** [comment]
对着新的API改了一下，应该都解决了

**Comment by Pacius** [comment]
Nice~确实可以了，就是默认这个`  add_option( 'kblog_danmaku_url', '//danmaku.daoapp.io' );`应该有个`/`结尾，要不貌似不能链接Dplayer-node
