### ISSUE TITLE
为什么。。现在一个文章中不能加载多个Dplayer？

### ISSUE THREAD

**Issue by ootd2322** [BlueCocoa/DPlayer-WordPress#12]
为什么。。现在一个文章中不能加载多个Dplayer？

**Comment by ootd2322** [comment]
为什么要删除这个东西？ 我用回了旧版本，是可以在一个页面或者文章中使用多个Dplayer播放器。。然后我可以利用这个功能来做选集数。为什么新版本要禁止多个。。。我有点不明白。。

**Comment by ootd2322** [comment]
哈。。用回了旧版。然后添加了那个互斥的功能，再修改调用的JS。完美实现同一页面，多个播放器。一个播放后其它暂停！！！舒服啊

**Comment by asleep2** [comment]
@a398496800  你现在用的版本是？ 你用的版本能hls.js吗？

**Comment by BlueCocoa** [comment]
不能使用多个？

**Comment by ootd2322** [comment]
> 不能使用多个？

是的，之前旧版本还可以。升级到那个有互斥设置的版本就不能多个存在。多个存在只会显示一个，其它就没意义了。

**Comment by BlueCocoa** [comment]
更新了1.2.5，应该没问题了
