### ISSUE TITLE
大佬，为什么手机上只能等到影片完全加载后才能看？

### ISSUE THREAD

**Issue by littleplus** [BlueCocoa/DPlayer-WordPress#4]
用谷歌chrome模拟手机分辨率倒是可以，但是如果用手机浏览器打开的话就无法加载

**Comment by BlueCocoa** [comment]
DPlayer里面用的就是&lt;video&gt;标签，只是在对应的那层video上加了弹幕的layer，所以这个甩锅给你的手机。

**Comment by littleplus** [comment]
那有没有什么比较容易的好的解决方法

**Comment by DIYgod** [comment]
手机型号和浏览器是啥

之前收到过这种奇怪的问题 https://github.com/DIYgod/DPlayer/issues/48

**Comment by littleplus** [comment]
噗，这个就是我发的....Nubia Z9 MAX，自带的浏览器，X浏览器，Via浏览器都是这样

**Comment by DIYgod** [comment]
那好的解决方法只有换手机了...

**Comment by littleplus** [comment]
好吧，谢谢大佬，我去试试/手动滑稽
