### ISSUE TITLE
你好，请问可以设置默认音量么？

### ISSUE THREAD

**Issue by ghost** [BlueCocoa/DPlayer-WordPress#7]
我想让这个播放器的默认音量是最大，但是每次刷新之后又变小了。

**Comment by DIYgod** [comment]
新版刚加了记忆音量的功能，更新DPlayer即可@BlueCocoa

**Comment by BlueCocoa** [comment]
呜哇，好的www
（前几天跟小伙伴在外面玩，没注意更新2333

**Comment by BlueCocoa** [comment]
然后窝发现DPlayer好像没更新release，这边以后直接跟DPlayer的master走没问题喵~? @DIYgod

**Comment by BlueCocoa** [comment]
This issue should be solved in version 1.2.0. Check for the update in your WordPress~
 (If not, please reopen this issue)

**Comment by ghost** [comment]
我升级这个插件到1.2.1版本后，发现刷新后音量并没有保持在刷新前的大小，但是我看了看demo，那里倒是可以记住音量。

**Comment by BlueCocoa** [comment]
BootCDN上的好像还没有跟上master的进度，我换unpkg吧

**Comment by DIYgod** [comment]
@BlueCocoa unpkg在国外，访问速度挺慢的...

**Comment by BlueCocoa** [comment]
😂那就等等bootcdn吧

**Comment by DIYgod** [comment]
@BlueCocoa bootcdn更新太慢了，推荐使用@Showfom 的 [CSS.NET](https://css.net/)

libs：https://cdnjs.cat.net/ajax/libs/dplayer/
版本信息：https://cdnjs.cat.net/ajax/libs/dplayer/package.json

**Comment by egoist** [comment]
用 jsdelivr.net 吧，支持 npm 和 git

**Comment by BlueCocoa** [comment]
那就先钦定为@DIYgod 推荐的 [CSS.NET](https://css.net/) 吧，，待会push~

**Comment by DIYgod** [comment]
@egoist 虽然有国内节点但速度貌似还是 CSS.NET 更快一些，考虑到这个插件几乎都是国内用户
