### ISSUE TITLE
Danmaku import issues

### ISSUE THREAD

**Issue by william9933** [BlueCocoa/DPlayer-WordPress#9]
Hello, I noticed that the default Danmaku API, "https://api.prprpr.me/dplayer/", had its certificate expired. Is that possible for the developer to add support for the local xml danmaku or local ass subtitle import? (Wordpress shortcode) Thanks.

**Comment by DIYgod** [comment]
API fixed.

**Comment by DIYgod** [comment]
Xml danmaku and  ass subtitle are not supported.

**Comment by wehaha** [comment]
应该怎么用啊？是作为插件下载解压 放到插件里面吗？

**Comment by DIYgod** [comment]
@wehaha http://bfy.tw/FwfH
